auth:
  existingSecret: my-postgres-secret
  username: devuser
  database: devdb
  # passwords stored in secret

primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 31253   # any 30k port

persistence:
  enabled: true
  size: 5Gi

